INSERT INTO TestFile2 (CVX Code, CVX Short Description, Full Vaccine Name, Note, VaccineStatus, internalID, nonvaccine, update_date) VALUES 
('54','adenovirus, type 4','adenovirus vaccine, type 4, live, oral','','Inactive','1.0','False','40326.0'),
('55','adenovirus, type 7','adenovirus vaccine, type 7, live, oral','','Inactive','2.0','False','40326.0'),
('82','adenovirus, unspecified formulation','adenovirus vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a adenovirus vaccination when noted on a vaccination card)','Inactive','3.0','False','40451.0'),
('24','anthrax','anthrax vaccine','','Active','4.0','False','43627.0'),
('19','BCG','Bacillus Calmette-Guerin vaccine','','Active','5.0','False','40326.0'),
('27','botulinum antitoxin','botulinum antitoxin','','Active','6.0','True','44078.0'),
('26','cholera, unspecified formulation','cholera vaccine, unspecified formulation','','Inactive','7.0','False','42538.0'),
('29','CMVIG','cytomegalovirus immune globulin, intravenous','','Active','8.0','True','44078.0'),
('56','dengue fever','dengue fever vaccine','Applies to dengue tetravalent product (e.g. DENGVAXIA)','Active','9.0','False','43732.0'),
('12','diphtheria antitoxin','diphtheria antitoxin','','Active','10.0','True','44078.0'),
('28','DT (pediatric)','diphtheria and tetanus toxoids, adsorbed for pediatric use','','Active','11.0','False','40326.0'),
('20','DTaP','diphtheria, tetanus toxoids and acellular pertussis vaccine','','Active','12.0','False','40326.0'),
('106','DTaP, 5 pertussis antigens','diphtheria, tetanus toxoids and acellular pertussis vaccine, 5 pertussis antigens','','Active','13.0','False','40326.0'),
('107','DTaP, unspecified formulation','diphtheria, tetanus toxoids and acellular pertussis vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a DTaP vaccination when noted on a vaccination card)','Inactive','14.0','False','40451.0'),
('110','DTaP-Hep B-IPV','DTaP-hepatitis B and poliovirus vaccine','','Active','15.0','False','40326.0'),
('50','DTaP-Hib','DTaP-Haemophilus influenzae type b conjugate vaccine','','Inactive','16.0','False','42814.0'),
('120','DTaP-Hib-IPV','diphtheria, tetanus toxoids and acellular pertussis vaccine, Haemophilus influenzae type b conjugate, and poliovirus vaccine, inactivated (DTaP-Hib-IPV)','','Active','17.0','False','40326.0'),
('130','DTaP-IPV','Diphtheria, tetanus toxoids and acellular pertussis vaccine, and poliovirus vaccine, inactivated','','Active','19.0','False','40326.0'),
('01','DTP','diphtheria, tetanus toxoids and pertussis vaccine','','Inactive','21.0','False','40326.0'),
('22','DTP-Hib','DTP-Haemophilus influenzae type b conjugate vaccine','','Inactive','22.0','False','42817.0'),
('102','DTP-Hib-Hep B','DTP- Haemophilus influenzae type b conjugate and hepatitis b vaccine','This CVX has been corrected. This non-US vaccine contained DTP, Hib and Hep B. It was withdrawn in 2007 .','Non-US','23.0','False','42510.0'),
('57','hantavirus','hantavirus vaccine','','Never Active','24.0','False','44083.0'),
('52','Hep A, adult','hepatitis A vaccine, adult dosage','','Active','25.0','False','40326.0'),
('83','Hep A, ped/adol, 2 dose','hepatitis A vaccine, pediatric/adolescent dosage, 2 dose schedule','','Active','26.0','False','40326.0'),
('84','Hep A, ped/adol, 3 dose','hepatitis A vaccine, pediatric/adolescent dosage, 3 dose schedule','This vaccine formulation is inactive and should not be used, except to record historic vaccinations with this formulation.','Inactive','27.0','False','40326.0'),
('31','Hep A, pediatric, unspecified formulation','hepatitis A vaccine, pediatric dosage, unspecified formulation','Do NOT use this code.  If formulation is unknown, use CVX 85.  There is only one formulation of Hep A, peds.','Inactive','28.0','False','40451.0'),
('85','Hep A, unspecified formulation','hepatitis A vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a HepA vaccination when noted on a vaccination card)','Inactive','29.0','False','40451.0'),
('104','Hep A-Hep B','hepatitis A and hepatitis B vaccine','','Active','30.0','False','40326.0'),
('30','HBIG','hepatitis B immune globulin','','Active','31.0','True','44078.0'),
('08','Hep B, adolescent or pediatric','hepatitis B vaccine, pediatric or pediatric/adolescent dosage','This code applies to any standard pediatric formulation of Hepatitis B vaccine. It should not be used for the 2-dose hepatitis B schedule for adolescents (11-15 year olds). It requires Merck's Recombivax HB adult formulation. Use code 43 for that vaccine.','Active','32.0','False','43230.0'),
('42','Hep B, adolescent/high risk infant','hepatitis B vaccine, adolescent/high risk infant dosage','As of August 27, 1998, Merck ceased distribution of their adolescent/high risk infant hepatitis B vaccine dosage. Code 42 should only be used to record historical records. For current administration of hepatitis B vaccine, pediatric/adolescent dosage, use code 08.','Inactive','33.0','False','40326.0'),
('43','Hep B, adult','hepatitis B vaccine, adult dosage','As of September 1999, a 2-dose hepatitis B schedule for adolescents (11-15 year olds) was FDA approved for Merck's Recombivax HB adult formulation. Use code 43 for the 2-dose. This code should be used for any use of standard adult formulation of hepatitis B vaccine.','Active','34.0','False','43230.0'),
('44','Hep B, dialysis','hepatitis B vaccine, dialysis patient dosage','NDCs that are used for both vaccine and dialysis (e.g. Engerix-B)  are mapped to CVX 43 which is not specific to dialysis use','Active','35.0','False','43593.0'),
('45','Hep B, unspecified formulation','hepatitis B vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a HepB vaccination when noted on a vaccination card)','Inactive','36.0','False','40451.0'),
('58','Hep C','hepatitis C vaccine','','Never Active','37.0','False','44083.0'),
('59','Hep E','hepatitis E vaccine','','Never Active','38.0','False','44083.0'),
('60','herpes simplex 2','herpes simplex virus, type 2 vaccine','','Never Active','39.0','False','44083.0'),
('46','Hib (PRP-D)','Haemophilus influenzae type b vaccine, PRP-D conjugate','','Inactive','40.0','False','40326.0'),
('47','Hib (HbOC)','Haemophilus influenzae type b vaccine, HbOC conjugate','','Inactive','41.0','False','40326.0'),
('48','Hib (PRP-T)','Haemophilus influenzae type b vaccine, PRP-T conjugate','','Active','42.0','False','40326.0'),
('49','Hib (PRP-OMP)','Haemophilus influenzae type b vaccine, PRP-OMP conjugate','','Active','43.0','False','40326.0'),
('17','Hib, unspecified formulation','Haemophilus influenzae type b vaccine, conjugate unspecified formulation','','Inactive','44.0','False','40451.0'),
('51','Hib-Hep B','Haemophilus influenzae type b conjugate and Hepatitis B vaccine','This vaccine may still be in use until the existing lots expire on 8/19/16.','Inactive','45.0','False','42440.0'),
('61','HIV','human immunodeficiency virus vaccine','','Never Active','46.0','False','44083.0'),
('118','HPV, bivalent','human papilloma virus vaccine, bivalent','','Inactive','47.0','False','40326.0'),
('62','HPV, quadrivalent','human papilloma virus vaccine, quadrivalent','','Active','49.0','False','43984.0'),
('86','IG','immune globulin, intramuscular','','Active','51.0','True','44078.0'),
('87','IGIV','immune globulin, intravenous','','Active','52.0','True','44078.0'),
('14','IG, unspecified formulation','immune globulin, unspecified formulation','','Inactive','53.0','True','44078.0'),
('111','influenza, live, intranasal','influenza virus vaccine, live, attenuated, for intranasal use','LAIV3','Inactive','54.0','False','41904.0'),
('15','influenza, split (incl. purified surface antigen)','influenza virus vaccine, split virus (incl. purified surface antigen)-retired CODE','This code is being retired. It will still be found in older immunization records. It included both preservative free and non-preservative free.','Inactive','55.0','False','40451.0'),
('16','influenza, whole','influenza virus vaccine, whole virus','','Inactive','56.0','False','40326.0'),
('88','influenza, unspecified formulation','influenza virus vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a Influenza vaccination when noted on a vaccination card)','Inactive','57.0','False','40451.0'),
('123','influenza, H5N1-1203','influenza virus vaccine, H5N1, A/Vietnam/1203/2004 (national stockpile)','','Inactive','58.0','False','40326.0'),
('10','IPV','poliovirus vaccine, inactivated','','Active','60.0','False','40326.0'),
('02','OPV','trivalent poliovirus vaccine, live, oral','This is the OPV that was used in the US','Inactive','61.0','False','42776.0'),
('89','polio, unspecified formulation','poliovirus vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a polio vaccination when noted on a vaccination card)','Inactive','62.0','False','40451.0'),
('39','Japanese encephalitis SC','Japanese Encephalitis Vaccine SC','','Inactive','63.0','False','42271.0'),
('63','Junin virus','Junin virus vaccine','','Never Active','64.0','False','44083.0'),
('64','leishmaniasis','leishmaniasis vaccine','','Never Active','65.0','False','44083.0'),
('65','leprosy','leprosy vaccine','','Never Active','66.0','False','44083.0'),
('66','Lyme disease','Lyme disease vaccine','','Inactive','67.0','False','40326.0'),
('03','MMR','measles, mumps and rubella virus vaccine','','Active','68.0','False','40326.0'),
('04','M/R','measles and rubella virus vaccine','','Inactive','69.0','False','40326.0'),
('94','MMRV','measles, mumps, rubella, and varicella virus vaccine','','Active','70.0','False','40326.0'),
('67','malaria','malaria vaccine','','Never Active','71.0','False','44083.0'),
('05','measles','measles virus vaccine','','Inactive','72.0','False','40421.0'),
('68','melanoma','melanoma vaccine','','Never Active','73.0','False','44083.0'),
('32','meningococcal MPSV4','meningococcal polysaccharide vaccine (MPSV4)','','Inactive','74.0','False','43035.0'),
('103','meningococcal C conjugate','meningococcal C conjugate vaccine','','Inactive','75.0','False','40326.0'),
('114','meningococcal MCV4P','meningococcal polysaccharide (groups A, C, Y and W-135) diphtheria toxoid conjugate vaccine (MCV4P)','','Active','76.0','False','40326.0'),
('108','meningococcal ACWY, unspecified formulation','meningococcal ACWY vaccine, unspecified formulation','This CVX is intended for use when one of the meningococcal vaccines containing serogroups A, C, W and Y (conjugate or polysaccaride) was given and the exact formulation was not recorded. It should not be used to record newly administered immunizations. It is not to be used when one of the meningococcal vaccines containing other serogroups was administered.','Inactive','77.0','False','42339.0'),
('07','mumps','mumps virus vaccine','','Inactive','79.0','False','42173.0'),
('69','parainfluenza-3','parainfluenza-3 virus vaccine','','Inactive','80.0','False','40326.0'),
('11','pertussis','pertussis vaccine','','Inactive','81.0','False','40326.0'),
('23','plague','plague vaccine','','Inactive','82.0','False','43237.0'),
('33','pneumococcal polysaccharide PPV23','pneumococcal polysaccharide vaccine, 23 valent','','Active','83.0','False','40326.0'),
('100','pneumococcal conjugate PCV 7','pneumococcal conjugate vaccine, 7 valent','','Inactive','84.0','False','41816.0'),
('109','pneumococcal, unspecified formulation','pneumococcal vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a pneumococcal vaccination when noted on a vaccination card)','Inactive','85.0','False','40451.0'),
('70','Q fever','Q fever vaccine','','Never Active','86.0','False','44083.0'),
('18','rabies, intramuscular injection','rabies vaccine, for intramuscular injection RETIRED CODE','This CVX code has been retired. It is replace by CVX 175,  or CVX 176. It will continue to be found in historic records.','Inactive','87.0','False','42661.0'),
('40','rabies, intradermal injection','rabies vaccine, for intradermal injection','','Inactive','88.0','False','42173.0'),
('90','rabies, unspecified formulation','rabies vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a rabies vaccination when noted on a vaccination card)','Inactive','89.0','False','40451.0'),
('72','rheumatic fever','rheumatic fever vaccine','','Never Active','90.0','False','44083.0'),
('73','Rift Valley fever','Rift Valley fever vaccine','','Never Active','91.0','False','44083.0'),
('34','RIG','rabies immune globulin','','Active','92.0','True','44078.0'),
('119','rotavirus, monovalent','rotavirus, live, monovalent vaccine','','Active','93.0','False','40326.0'),
('122','rotavirus, unspecified formulation','rotavirus vaccine, unspecified formulation','','Inactive','95.0','False','40451.0'),
('116','rotavirus, pentavalent','rotavirus, live, pentavalent vaccine','','Active','97.0','False','40326.0'),
('74','rotavirus, tetravalent','rotavirus, live, tetravalent vaccine','','Inactive','99.0','False','40326.0'),
('71','RSV-IGIV','respiratory syncytial virus immune globulin, intravenous','','Active','101.0','True','44078.0'),
('93','RSV-MAb','respiratory syncytial virus monoclonal antibody (palivizumab), intramuscular','','Active','102.0','True','44078.0'),
('06','rubella','rubella virus vaccine','','Inactive','103.0','False','42173.0'),
('38','rubella/mumps','rubella and mumps virus vaccine','','Inactive','104.0','False','40326.0'),
('76','Staphylococcus bacterio lysate','Staphylococcus bacteriophage lysate','','Inactive','105.0','True','44078.0'),
('113','Td (adult), 5 Lf tetanus toxoid, preservative free, adsorbed','tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use (5 Lf of tetanus toxoid and 2 Lf of diphtheria toxoid)','','Active','106.0','False','43035.0'),
('09','Td (adult), 2 Lf tetanus toxoid, preservative free, adsorbed','tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use (2 Lf of tetanus toxoid and 2 Lf of diphtheria toxoid)','','Active','107.0','False','43035.0'),
('115','Tdap','tetanus toxoid, reduced diphtheria toxoid, and acellular pertussis vaccine, adsorbed','','Active','108.0','False','40326.0'),
('35','tetanus toxoid, adsorbed','tetanus toxoid, adsorbed','','Inactive','110.0','False','42230.0'),
('112','tetanus toxoid, unspecified formulation','tetanus toxoid, unspecified formulation','','Inactive','111.0','False','40451.0'),
('77','Tick-borne encephalitis vaccine (non-US)','Tick-borne encephalitis vaccine (non-US)','Non-US vaccine','Non-US','112.0','False','44624.0'),
('13','TIG','tetanus immune globulin','','Active','113.0','True','44078.0'),
('95','TST-OT tine test','tuberculin skin test; old tuberculin, multipuncture device','TB Skin test is not vaccine.','Inactive','114.0','True','44078.0'),
('96','TST-PPD intradermal','tuberculin skin test; purified protein derivative solution, intradermal','TB Skin test is not vaccine.','Inactive','115.0','True','44078.0'),
('97','TST-PPD tine test','tuberculin skin test; purified protein derivative, multipuncture device','TB Skin test is not vaccine.','Inactive','116.0','True','44078.0'),
('98','TST, unspecified formulation','tuberculin skin test; unspecified formulation','TB Skin test is not vaccine.','Inactive','117.0','True','44078.0'),
('78','tularemia vaccine','tularemia vaccine','','Inactive','118.0','False','40326.0'),
('91','typhoid, unspecified formulation','typhoid vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a typhoid vaccination when noted on a vaccination card)','Inactive','119.0','False','40451.0'),
('25','typhoid, oral','typhoid vaccine, live, oral','','Active','120.0','False','40326.0'),
('41','typhoid, parenteral','typhoid vaccine, parenteral, other than acetone-killed, dried','','Inactive','121.0','False','42229.0'),
('53','typhoid, parenteral, AKD (U.S. military)','typhoid vaccine, parenteral, acetone-killed, dried (U.S. military)','','Inactive','122.0','False','42173.0'),
('101','typhoid, ViCPs','typhoid Vi capsular polysaccharide vaccine','','Active','123.0','False','40326.0'),
('75','vaccinia (smallpox)','vaccinia (smallpox) vaccine','','Active','124.0','False','40326.0'),
('105','vaccinia (smallpox) diluted','vaccinia (smallpox) vaccine, diluted','','Inactive','125.0','False','40326.0'),
('79','vaccinia immune globulin','vaccinia immune globulin','','Active','126.0','True','44078.0'),
('21','varicella','varicella virus vaccine','','Active','127.0','False','40326.0'),
('81','VEE, inactivated','Venezuelan equine encephalitis, inactivated','','Inactive','128.0','False','40326.0'),
('80','VEE, live','Venezuelan equine encephalitis, live, attenuated','','Inactive','129.0','False','40326.0'),
('92','VEE, unspecified formulation','Venezuelan equine encephalitis vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a VEE vaccination when noted on a vaccination card)','Inactive','130.0','False','40451.0'),
('36','VZIG','varicella zoster immune globulin','','Active','131.0','True','44078.0'),
('117','VZIG (IND)','varicella zoster immune globulin (Investigational New Drug)','','Never Active','132.0','True','44083.0'),
('37','yellow fever','yellow fever vaccine','This is the YF vaccine that has been available in the US for years. It is stabilized with sorbitol and gelatin.','Active','134.0','False','42796.0'),
('121','zoster live','zoster vaccine, live','','Active','135.0','False','40326.0'),
('998','no vaccine administered','no vaccine administered','Code 998 was added for use in VXU HL7 messages where the OBX segment is nested with the RXA segment, but the message does not contain information about a vaccine administration. An example of this use is to report the vaccines due next for a patient when no vaccine administration is being reported.','Inactive','137.0','True','40326.0'),
('999','unknown','unknown vaccine or immune globulin','This CVX code has little utility and should rarely be used.','Inactive','138.0','True','44131.0'),
('99','RESERVED - do not use','RESERVED - do not use','Code 99 will not be used in this table to avoid confusion with code 999.','Inactive','139.0','True','44083.0'),
('133','Pneumococcal conjugate PCV 13','pneumococcal conjugate vaccine, 13 valent','','Active','141.0','False','40326.0'),
('134','Japanese Encephalitis IM','Japanese Encephalitis vaccine for intramuscular administration','','Active','142.0','False','40326.0'),
('137','HPV, unspecified formulation','HPV, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a HPV vaccination when noted on a vaccination card)','Inactive','144.0','False','40451.0'),
('136','Meningococcal MCV4O','meningococcal oligosaccharide (groups A, C, Y and W-135) diphtheria toxoid conjugate vaccine (MCV4O)','','Active','145.0','False','40326.0'),
('135','Influenza, high dose seasonal','influenza, high dose seasonal, preservative-free','','Active','146.0','False','40326.0'),
('131','typhus, historical','Historical record of a typhus vaccination','','Inactive','147.0','False','40326.0'),
('132','DTaP-IPV-HIB-HEP B, historical','Historical diphtheria and tetanus toxoids and acellular pertussis, poliovirus, Haemophilus b conjugate and hepatitis B (recombinant) vaccine.','This is not the same as CVX 146, Hexavalent vaccine.','Inactive','148.0','False','43230.0'),
('128','Novel Influenza-H1N1-09, all formulations','Novel influenza-H1N1-09, all formulations','This code is used whenever the actual formulation is not determined or when aggregating all Novel H1N1 Influenza-09 immunizations for reporting to CRA. It should not be used for seasonal influenza vaccine that is not otherwise specified. (NOS)','Inactive','149.0','False','40418.0'),
('125','Novel Influenza-H1N1-09, nasal','Novel Influenza-H1N1-09, live virus for nasal administration','','Inactive','150.0','False','40418.0'),
('126','Novel influenza-H1N1-09, preservative-free','Novel influenza-H1N1-09, preservative-free, injectable','','Inactive','151.0','False','40418.0'),
('127','Novel influenza-H1N1-09','Novel influenza-H1N1-09, injectable','','Inactive','152.0','False','40418.0'),
('138','Td (adult)','tetanus and diphtheria toxoids, not adsorbed, for adult use','Note that this Td is not adsorbed.','Inactive','154.0','False','40451.0'),
('139','Td(adult) unspecified formulation','Td(adult) unspecified formulation','This CVX code allows reporting of a historic vaccination when the formulation is unknown (for example, when recording a Td vaccination when noted on a vaccination card)','Inactive','155.0','False','43704.0'),
('140','Influenza, seasonal, injectable, preservative free','Influenza, seasonal, injectable, preservative free','IIV3. This vaccine code is one of two which replace CVX 15, influenza, split virus.','Active','156.0','False','41472.0'),
('129','Japanese Encephalitis, unspecified formulation','Japanese Encephalitis vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a JE vaccination when noted on a vaccination card)','Inactive','157.0','False','40451.0'),
('141','Influenza, seasonal, injectable','Influenza, seasonal, injectable','IIV3. This is one of two codes replacing CVX 15, which is being retired.','Active','159.0','False','41472.0'),
('142','tetanus toxoid, not adsorbed','tetanus toxoid, not adsorbed','','Inactive','160.0','False','42230.0'),
('143','Adenovirus types 4 and 7','Adenovirus, type 4 and type 7, live, oral','This vaccine is administered as 2 tablets.','Active','161.0','False','40622.0'),
('144','influenza, seasonal, intradermal, preservative free','seasonal influenza, intradermal, preservative free','IIV3','Active','162.0','False','41472.0'),
('145','RSV-MAb (new)','respiratory syncytial virus monoclonal antibody (motavizumab), intramuscular','','Never Active','163.0','True','44083.0'),
('146','DTaP,IPV,Hib,HepB','Diphtheria and Tetanus Toxoids and Acellular Pertussis Adsorbed, Inactivated Poliovirus, Haemophilus b Conjugate (Meningococcal Protein Conjugate), and Hepatitis B (Recombinant) Vaccine.','Note that this vaccine is different from CVX 132.','Active','164.0','False','43587.0'),
('147','meningococcal MCV4, unspecified formulation','Meningococcal, MCV4, unspecified conjugate formulation(groups A, C, Y and W-135)','This CVX should only be used for historical doses of meningococcal conjugate vaccine where the formulation is unknown (oligosaccharide vs polysaccharide). It is not the same as CVX 108, Meningococcal, unspecified formulation. This CVX is for unspecified Meningococcal conjugate vaccines.','Inactive','165.0','False','40947.0'),
('148','Meningococcal C/Y-HIB PRP','Meningococcal Groups C and Y and Haemophilus b Tetanus Toxoid Conjugate Vaccine','','Inactive','166.0','False','43231.0'),
('149','influenza, live, intranasal, quadrivalent','influenza, live, intranasal, quadrivalent','new in 2012.  LAIV4','Active','167.0','False','41472.0'),
('150','influenza, injectable, quadrivalent, preservative free','Influenza, injectable, quadrivalent, preservative free','New in 2012.  IIV4','Active','168.0','False','41472.0'),
('151','influenza nasal, unspecified formulation','influenza nasal, unspecified formulation','This CVX should only be used for historical records where the formulation of nasal flu vaccine is not known.','Inactive','169.0','False','41302.0'),
('152','Pneumococcal Conjugate, unspecified formulation','Pneumococcal Conjugate, unspecified formulation','This CVX should only be used for historical records where the formulation of pneumococcal conjugate vaccine is not known.','Inactive','170.0','False','41302.0'),
('153','Influenza, injectable, MDCK, preservative free','Influenza, injectable, Madin Darby Canine Kidney, preservative free','ccIIV3','Inactive','171.0','False','42545.0'),
('154','Hep A, IG','Hepatitis A immune globulin','Do not use this code. This product may be used for Hep A and other viral infections. The correct vaccine / CVX is 86 (IG).','Never Active','172.0','True','44083.0'),
('155','influenza, recombinant, injectable, preservative free','Seasonal, trivalent, recombinant, injectable influenza vaccine, preservative free','RIV','Active','173.0','False','41472.0'),
('156','Rho(D)-IG','Rho(D) Immune globulin- IV or IM','This immune globulin may be administered either IM or IV.','Active','174.0','True','44078.0'),
('157','Rho(D) -IG IM','Rho(D) Immune globulin - IM','This immune globulin may be administered IM only.','Active','175.0','True','44078.0'),
('158','influenza, injectable, quadrivalent','influenza, injectable, quadrivalent, contains preservative','New in 2013.  IIV4','Active','176.0','False','41506.0'),
('159','Rho(D) - Unspecified formulation','Rho(D) Unspecified formulation','','Inactive','177.0','True','44078.0'),
('160','Influenza A monovalent (H5N1), ADJUVANTED-2013','Influenza A monovalent (H5N1), adjuvanted, National stockpile 2013','Approved by FDA 2013, adjuvant is mixed at point of administration.','Active','178.0','False','41786.0'),
('801','AS03 Adjuvant','AS03 Adjuvant','This is the adjuvant that is packaged with H5N1 vaccine, adjuvanted','Active','179.0','True','44131.0'),
('161','Influenza, injectable,quadrivalent, preservative free, pediatric','Influenza, injectable,quadrivalent, preservative free, pediatric','','Active','180.0','False','41843.0'),
('162','meningococcal B, recombinant','meningococcal B vaccine, fully recombinant','','Active','181.0','False','41946.0'),
('163','meningococcal B, OMV','meningococcal B vaccine, recombinant, OMV, adjuvanted','','Active','182.0','False','42037.0'),
('164','meningococcal B, unspecified','meningococcal B, unspecified formulation','','Inactive','183.0','False','41946.0'),
('165','HPV9','Human Papillomavirus 9-valent vaccine','','Active','184.0','False','41984.0'),
('166','influenza, intradermal, quadrivalent, preservative free','influenza, intradermal, quadrivalent, preservative free, injectable','','Active','185.0','False','41988.0'),
('167','meningococcal, unknown serogroups','meningococcal vaccine of unknown formulation and unknown serogroups','This CVX is intended for use when any one of the meningococcal vaccines is recorded and there is no information about which serogroups are protected against. This code should not be used when a newly administered immunization is recorded.','Inactive','188.0','False','42339.0'),
('168','influenza, trivalent, adjuvanted','Seasonal trivalent influenza vaccine, adjuvanted, preservative free','','Active','189.0','False','42348.0'),
('169','Hep A, live attenuated','Hep A, live attenuated-IM','This vaccine is not available in the US.','Non-US','190.0','False','42500.0'),
('170','DTAP/IPV/HIB - non-US','non-US diphtheria, tetanus toxoids and acellular pertussis vaccine, Haemophilus influenzae type b conjugate, and poliovirus vaccine, inactivated (DTaP-Hib-IPV)','This CVX was split off from CVX 102, to correctly identify the contents of the vaccine.','Non-US','191.0','False','42510.0'),
('171','Influenza, injectable, MDCK, preservative free, quadrivalent','Influenza, injectable, Madin Darby Canine Kidney, preservative free, quadrivalent','','Active','192.0','False','42537.0'),
('172','cholera, WC-rBS','cholera, WC-rBS','','Non-US','193.0','False','42538.0'),
('173','cholera, BivWC','cholera, BivWC','','Non-US','194.0','False','42538.0'),
('174','cholera, live attenuated','cholera, live attenuated','','Active','195.0','False','42538.0'),
('175','Rabies - IM Diploid cell culture','Human Rabies vaccine from human diploid cell culture','','Active','196.0','False','42661.0'),
('176','Rabies - IM fibroblast culture','Human rabies vaccine from Chicken fibroblast culture','','Active','197.0','False','42661.0'),
('177','PCV10','pneumococcal conjugate vaccine, 10 valent','This is a foreign vaccine','Non-US','201.0','False','42723.0'),
('178','OPV bivalent','Non-US bivalent oral polio vaccine (types 1 and 3)','This is a non-US vaccine that may be seen in some immunization histories.','Non-US','202.0','False','42752.0'),
('179','OPV ,monovalent, unspecified','Non-US monovalent oral polio vaccine, unspecified formulation','This is a non-US vaccine that may be seen in some immunization histories. It is composed of either Type 1, Type 2 or Type 3 oral polio vaccine.','Non-US','203.0','False','42752.0'),
('180','tetanus immune globulin','tetanus immune globulin','This record duplicates CVX 13 (TIG). Do not use CVX 180.','Inactive','204.0','True','44083.0'),
('181','anthrax immune globulin','anthrax immune globulin','','Active','205.0','True','44078.0'),
('182','OPV, Unspecified','Oral Polio Vaccine, Unspecified formulation','This code represents an oral polio vaccine where the specific formulation is unknown.','Inactive','206.0','False','42752.0'),
('183','Yellow fever vaccine - alt','Yellow fever vaccine alternative formulation','This vaccine is stabilized with sorbitol and lactose and has been used outside the US for some time. It will be made available in the US.','Active','207.0','False','42796.0'),
('184','Yellow fever, unspecified formulation','Yellow fever vaccine, unspecified formulation','','Inactive','208.0','False','42796.0'),
('185','influenza, recombinant, quadrivalent,injectable, preservative free','Seasonal, quadrivalent, recombinant, injectable influenza vaccine, preservative free','','Active','209.0','False','42846.0'),
('186','Influenza, injectable, MDCK, quadrivalent, preservative','Influenza, injectable, Madin Darby Canine Kidney,  quadrivalent with preservative','','Active','210.0','False','42913.0'),
('187','zoster recombinant','zoster vaccine recombinant','','Active','211.0','False','43035.0'),
('188','zoster, unspecified formulation','zoster vaccine, unspecified formulation','This CVX code allows reporting of a vaccination when formulation is unknown (for example, when recording a zoster vaccination when noted on a vaccination card)','Inactive','212.0','False','43035.0'),
('189','HepB-CpG','Hepatitis B vaccine (recombinant), CpG adjuvanted','','Active','213.0','False','43230.0'),
('190','Typhoid conjugate vaccine (TCV)','Typhoid conjugate vaccine (non-US)','','Non-US','214.0','False','44400.0'),
('191','meningococcal A polysaccharide (non-US)','meningococcal A polysaccharide vaccine (non-US)','','Non-US','215.0','False','43230.0'),
('192','meningococcal AC polysaccharide (non-US)','meningococcal AC polysaccharide vaccine (non-US)','','Non-US','216.0','False','43230.0'),
('193','Hep A-Hep B, pediatric/adolescent','hepatitis A and hepatitis B vaccine, pediatric/adolescent (non-US)','e.g. Twinrix Junior available in Canada','Non-US','217.0','False','43333.0'),
('194','Influenza, Southern Hemisphere','influenza, Southern Hemisphere, unspecified formulation','This CVX code should be used to record administration of Southern Hemisphere influenza vaccine where formulation is unknown','Inactive','218.0','False','44028.0'),
('195','DT, IPV adsorbed','Diphtheria, Tetanus, Poliomyelitis adsorbed','This code should be used to document non-US vaccines for DT,IPV such as Revaxis','Non-US','219.0','False','43676.0'),
('196','Td, adsorbed, preservative free, adult use, Lf unspecified','tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use, Lf unspecified','Used when Td Lf specification is unknown','Active','220.0','False','43692.0'),
('197','influenza, high-dose, quadrivalent','influenza, high-dose seasonal, quadrivalent, .7mL dose, preservative free','Target population 65 and older, starting season 2020/2021','Active','221.0','False','44034.0'),
('200','influenza, Southern Hemisphere, pediatric, preservative free','influenza, seasonal, Southern Hemisphere, quadrivalent, pediatric 0.25mL dose, preservative free','Pediatric dose for ages 6-35 months','Active','222.0','False','43957.0'),
('201','influenza, Southern Hemisphere, preservative free','influenza, seasonal, Southern Hemisphere, quadrivalent, 0.5mL dose, no preservative','Represents single dose vial','Active','223.0','False','43957.0'),
('202','influenza, Southern Hemisphere, quadrivalent, with preservative','influenza, seasonal, Southern Hemisphere, quadrivalent, 0.5mL dose, with preservative','Represents multi-dose vial','Active','224.0','False','43957.0'),
('198','DTP-hepB-Hib Pentavalent Non-US','Diphtheria, pertussis, tetanus, hepatitis B, Haemophilus Influenza Type b, (Pentavalent)','This represents the non-US pentavalent vaccine.  Should be used for historic documentation in US','Non-US','225.0','False','43943.0'),
('203','meningococcal polysaccharide (groups A, C, Y, W-135) TT conjugate','meningococcal polysaccharide (groups A, C, Y, W-135) tetanus toxoid conjugate vaccine .5mL dose, preservative free','','Active','226.0','False','43978.0'),
('205','Influenza vaccine, quadrivalent, adjuvanted','influenza, seasonal vaccine, quadrivalent, adjuvanted, .5mL dose, preservative free','','Active','228.0','False','44034.0'),
('206','Smallpox monkeypox vaccine (National Stockpile)','Vaccinia, smallpox monkeypox vaccine, live attenuated, preservative free (National Stockpile)','National Stockpile Only. FDA US Licensed products JYNNEOS (also brandnames IMVAMUNE, IMVANEX) ','Active','229.0','False','44624.0'),
('207','COVID-19, mRNA, LNP-S, PF, 100 mcg/0.5mL dose or 50 mcg/0.25mL dose','SARS-COV-2 (COVID-19) vaccine, mRNA, spike protein, LNP, preservative free, 100 mcg/0.5mL dose or 50 mcg/0.25mL dose','FDA EUA 12/18/2020, 2-dose vaccine.  Used to record Moderna vaccines administered in the US and in non-US locations (includes tradename Spikevax)','Active','230.0','False','44601.0'),
('208','COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose','SARS-COV-2 (COVID-19) vaccine, mRNA, spike protein, LNP, preservative free, 30 mcg/0.3mL dose','FDA BLA 08/23/2021 for adult dose (16+ years). Still under EUA for adolescent doses and presentations. EUA 12/11/2020, 2-dose vaccine. Used to record Pfizer vaccines administered in the US and in non-US locations (includes tradename Comirnaty)','Active','231.0','False','44449.0'),
('213','SARS-COV-2 (COVID-19) vaccine, UNSPECIFIED','SARS-COV-2 (COVID-19) vaccine, UNSPECIFIED','Unspecified code for COVID-19 not to be used to record patient US administration. May be used to record historic US administration if product not known.  CVX code 500 should be used to record Non-US vaccine where product is not known.','Inactive','232.0','False','44408.0'),
('210','COVID-19 vaccine, vector-nr, rS-ChAdOx1, PF, 0.5 mL ','SARS-COV-2 (COVID-19) vaccine, vector non-replicating, recombinant spike protein-ChAdOx1, preservative free, 0.5 mL ','Potential FDA EUA, 2-dose vaccine. AstraZeneca vaccine is authorized by the WHO and recognized towards immunity in the US. Non-US WHO authorized tradenames/identifiers include VAXZEVRIA, AZD1222, ChAdOx1 nCoV-19, COVISHIELD','Non-US','233.0','False','44447.0'),
('212','COVID-19 vaccine, vector-nr, rS-Ad26, PF, 0.5 mL','SARS-COV-2 (COVID-19) vaccine, vector non-replicating, recombinant spike protein-Ad26, preservative free, 0.5 mL','FDA EUA 02/27/2021, 1-dose vaccine. Used to record Janssen/J&J vaccines administered in the US and in non-US locations','Active','234.0','False','44447.0'),
('204','Ebola Zaire vaccine, live, recombinant, 1mL dose','Ebola Zaire vaccine, live, recombinant, 1mL dose ','FDA Approval Pending','Active','235.0','False','44292.0'),
('214','Ebola, unspecified','Ebola, unspecified','','Inactive','236.0','False','44292.0'),
('211','COVID-19, subunit, rS-nanoparticle+Matrix-M1 Adjuvant, PF, 0.5 mL','SARS-COV-2 (COVID-19) vaccine, subunit, recombinant spike protein-nanoparticle+Matrix-M1 Adjuvant, preservative free, 0.5mL dose','Pre-EUA Authorization - Novavax Primary Series dose','Active','237.0','False','44630.0'),
('500','COVID-19 Non-US Vaccine, Product Unknown','SARS-COV-2 COVID-19 Non-US Vaccine, Specific Product Unknown','Pandemic Non-US Covid Administration - specific CVX or product unknown ','Non-US','238.0','False','44392.0'),
('501','COVID-19 IV Non-US Vaccine (QAZCOVID-IN)','SARS-COV-2 COVID-19 Inactivated Virus Non-US Vaccine Product (QAZCOVID-IN)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','239.0','False','44392.0'),
('502','COVID-19 IV Non-US Vaccine (COVAXIN)','SARS-COV-2 COVID-19 Inactivated Virus Non-US Vaccine Product (COVAXIN)','Pandemic Non-US Vaccine Authorized by WHO 11-3-2021, recognized toward immunity in US, https://extranet.who.int/pqweb/vaccines/who-recommendation-bharat-biotech-international-ltd-covid-19-vaccine-whole-virion','Non-US','240.0','False','44519.0'),
('503','COVID-19 LAV Non-US Vaccine (COVIVAC)','SARS-COV-2 COVID-19  Live Attenuated Virus Non-US Vaccine Product (COVIVAC)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','241.0','False','44392.0'),
('504','COVID-19 VVnr Non-US Vaccine (Sputnik Light)','SARS-COV-2 COVID-19 Viral Vector Non-replicating Non-US Vaccine Product (Sputnik Light)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','242.0','False','44392.0'),
('505','COVID-19 VVnr Non-US Vaccine (Sputnik V)','SARS-COV-2 COVID-19 Viral Vector Non-replicating Non-US Vaccine Product (Sputnik V)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','243.0','False','44392.0'),
('506','COVID-19 VVnr Non-US Vaccine (CanSino Biological Inc./Beijing Institute of Biotechnology)','SARS-COV-2 COVID-19 Viral Vector Non-replicating Non-US Vaccine Product (CanSino Biological Inc./Beijing Institute of Biotechnology)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','244.0','False','44392.0'),
('507','COVID-19 PS Non-US Vaccine (Anhui Zhifei Longcom Biopharm + Inst of Micro, Chinese Acad of Sciences)','SARS-COV-2 COVID-19 Protein Subunit Non-US Vaccine Product (Anhui Zhifei Longcom Biopharmaceutical + Institute of Microbiology, Chinese Academy of Sciences)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward immunity in US','Non-US','245.0','False','44426.0'),
('508','COVID-19 PS Non-US Vaccine (Jiangsu Province Centers for Disease Control and Prevention)','SARS-COV-2 COVID-19 Protein Subunit Non-US Vaccine Product  (Jiangsu Province Centers for Disease Control and Prevention)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','246.0','False','44392.0'),
('509','COVID-19 PS Non-US Vaccine (EpiVacCorona)','SARS-COV-2 COVID-19 Protein Subunit Non-US Vaccine Product (EpiVacCorona)','Pandemic Non-US Vaccine not Authorized by WHO - not counted toward  immunity in US','Non-US','247.0','False','44392.0'),
('510','COVID-19 IV Non-US Vaccine (BIBP, Sinopharm)','SARS-COV-2 COVID-19 Inactivated Virus Non-US Vaccine Product (BIBP, Sinopharm)','WHO authorized pandemic vaccine.  Recognized towards immunity in US','Non-US','248.0','False','44392.0'),
('511','COVID-19 IV Non-US Vaccine (CoronaVac, Sinovac)','SARS-COV-2 COVID-19 Inactivated Virus Non-US Vaccine Product (CoronaVac, Sinovac)','WHO authorized pandemic vaccine.  Recognized towards immunity in US','Non-US','249.0','False','44392.0'),
('215','Pneumococcal conjugate PCV15, polysaccharide CRM197 conjugate, adjuvant, PF','Pneumococcal conjugate vaccine 15-valent (PCV15), polysaccharide CRM197 conjugate, adjuvant, preservative free','','Active','250.0','False','44426.0'),
('216','Pneumococcal conjugate PCV20, polysaccharide CRM197 conjugate, adjuvant, PF','Pneumococcal conjugate vaccine 20-valent (PCV20), polysaccharide CRM197 conjugate, adjuvant, preservative free','','Active','251.0','False','44426.0'),
('219','COVID-19, mRNA, LNP-S, PF, 3 mcg/0.2 mL dose, tris-sucrose','SARS-COV-2 (COVID-19) vaccine, mRNA, spike protein, LNP, preservative free, 3 mcg/0.2mL dose, tris-sucrose formulation','Potential FDA EUA, Pfizer tris-sucrose vaccine for 6 mo through 4 years of age','Active','252.0','False','44602.0'),
('217','COVID-19, mRNA, LNP-S, PF, 30 mcg/0.3 mL dose, tris-sucrose','SARS-COV-2 (COVID-19) vaccine, mRNA, spike protein, LNP, preservative free, 30 mcg/0.3mL dose, tris-sucrose formulation','EUA 12+ yrs, BLA 16+ yrs Pfizer tris-sucrose formulation vaccine for ages 12 and older','Active','253.0','False','44606.0'),
('218','COVID-19, mRNA, LNP-S, PF, 10 mcg/0.2 mL dose, tris-sucrose','SARS-COV-2 (COVID-19) vaccine, mRNA, spike protein, LNP, preservative free, 10 mcg/0.2mL dose, tris-sucrose formulation','FDA EUA 01/03/2022, Pfizer tris-sucrose vaccine for 5 through 11 years of age','Active','254.0','False','44649.0'),
('220','HepB recombinant, 3-antigen, Al(OH)3','Hepatitis B vaccine (recombinant), 3-antigen, Al(OH)3 adjuvanted','New Hep B vaccine 1/2022','Active','255.0','False','44606.0'),
('221','COVID-19, mRNA, LNP-S, PF, 50 mcg/0.5 mL dose','SARS-COV-2 (COVID-19) vaccine, mRNA, spike protein, LNP, preservative free, 50 mcg/0.5 mL dose','FDA EUA 03/29/2022, Moderna booster dose 2.5mL vial presentation only','Active','256.0','False','44649.0'),
('222','Tick-borne encephalitis, unspecified','Tick-borne encephalitis vaccine, unspecified','Unspecified Code - should only be used when specific vaccine administered is unknown','Inactive','257.0','False','44623.0'),
('223','Tick-borne encephalitis, inactivated, PF, 0.25mL','Tick-borne encephalitis vaccine, inactivated, preservative free, 0.25mL dose','Pediatric dose vaccine','Active','258.0','False','44623.0'),
('224','Tick-borne encephalitis, inactivated, PF, 0.5mL','Tick-borne encephalitis vaccine, inactivated, preservative free, 0.5mL dose','Adult dose vaccine','Active','259.0','False','44624.0'),
('225','COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 5mcg/0.5mL','SARS-COV-2 (COVID-19) vaccine, D614, prefusion spike recombinant protein subunit (CoV2 preS dTM), AS03 adjuvant added, preservative free, 5mcg/0.5mL dose','Pre-EUA Authorization, Sanofi Booster dose - requires addition of AS03 adjuvant','Active','260.0','False','44630.0'),
('226','COVID-19, D614, recomb, preS dTM, AS03 adjuvant add, PF, 10mcg/0.5mL','SARS-COV-2 (COVID-19) vaccine, D614, prefusion spike recombinant protein subunit (CoV2 preS dTM), AS03 adjuvant added, preservative free, 10mcg/0.5mL dose','Pre-EUA Authorization, Sanofi Primary Series dose - requires addition of AS03 adjuvant','Pending','261.0','False','44630.0')